ALTER TABLE "User"
ADD COLUMN "tutorialStatus" TEXT NOT NULL DEFAULT 'NOT_STARTED',
ADD COLUMN "tutorialStep" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "tutorialState" JSONB,
ADD COLUMN "tutorialCompletedAt" TIMESTAMP(3);
